/tmp/slurmd/job48230645/slurm_script: line 0: unalias: pine: not found
/tmp/slurmd/job48230645/slurm_script: line 0: unalias: quota: not found
/tmp/slurmd/job48230645/slurm_script: line 0: unalias: chsh: not found
/tmp/slurmd/job48230645/slurm_script: line 0: unalias: grpe: not found
/tmp/slurmd/job48230645/slurm_script: line 0: unalias: alloc: not found
/tmp/slurmd/job48230645/slurm_script: line 0: unalias: vi: not found
/tmp/slurmd/job48230645/slurm_script: line 0: unalias: chfn: not found
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    .map(stack_bands)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 880, in map
    return MapDataset(self, map_func)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1868, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 475, in add_to_graph
    self._create_definition_if_needed()
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 331, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 340, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 804, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1853, in tf_map_func
    for t in nest.flatten(ret)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1853, in <listcomp>
    for t in nest.flatten(ret)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1011, in convert_to_tensor
    as_ref=False)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 424, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
